use crate::tools::constants::{
    DEN_BEAR_ENVIRONMENT, DEN_BEAR_GET_SELF, DEN_BEAR_LIST_MEMBERS, DEN_CAPABILITIES_LIST_SELF,
    DEN_CAPABILITY_DESCRIBE, DEN_CAPABILITY_SEARCH, DEN_CHANNEL_GET_CONTEXT,
    DEN_CONVERSATION_SET_TITLE, DEN_CORE_WRITE_RESULT_SUMMARY, DEN_ENTITY_BROWSE,
    DEN_ENTITY_LINK_MEMORY, DEN_ENTITY_MERGE, DEN_ENTITY_RESOLVE, DEN_ENTITY_SPLIT,
    DEN_ENTITY_WRITE_ACCESS_RULE, DEN_ENTITY_WRITE_ANCHOR, DEN_JOB_CREATE,
    DEN_JOB_EVALUATE_CRITERION, DEN_JOB_EXECUTE, DEN_JOB_GET, DEN_JOB_LIST, DEN_JOB_UPDATE,
    DEN_MEMORY_APPLY_CORE_UPDATE, DEN_MEMORY_CREATE_WORK_SURFACE_SCAFFOLD,
    DEN_MEMORY_LIST_PROPOSALS, DEN_MEMORY_MARK_LIFECYCLE, DEN_MEMORY_ORIENT_WORK_SURFACE,
    DEN_MEMORY_READ, DEN_MEMORY_READ_PROPOSAL, DEN_MEMORY_REQUEST_REVIEW,
    DEN_MEMORY_RESOLVE_PROPOSAL, DEN_MEMORY_SEARCH, DEN_MEMORY_STATUS, DEN_MEMORY_TREE,
    DEN_MEMORY_TREE_LEGACY_PROVIDER, DEN_MEMORY_WRITE_ENTRY, DEN_OBSERVATION_WRITE,
    DEN_PLAN_MODE_CANCEL, DEN_PLAN_MODE_ENTER, DEN_PLAN_MODE_EXIT, DEN_PLAN_MODE_RECORD_APPROVAL,
    DEN_PLAN_MODE_STATUS, DEN_POLICY_GET_SELF, DEN_PROMPT_MEMORY_LIST, DEN_PROMPT_MEMORY_PATCH,
    DEN_PROMPT_MEMORY_UPSERT, DEN_RUN_WRITE_RESULT, DEN_SITUATION_GET,
    DEN_SITUATION_GET_LEGACY_PROVIDER, DEN_SKILL_APPROVE_PROPOSAL, DEN_SKILL_PROPOSE,
    DEN_SKILL_REJECT_PROPOSAL, DEN_TASK_APPROVE_INTENT, DEN_TASK_CREATE, DEN_TASK_LIST,
    DEN_TASK_LISTS_GET_STATUS, DEN_TASK_LISTS_LIST, DEN_TASK_LISTS_REQUEST_HANDOFF,
    DEN_TASK_LISTS_UPDATE, DEN_TASK_LIST_CHECKOUT, DEN_TASK_LIST_SYNC, DEN_TASK_REJECT_INTENT,
    DEN_TASK_UPDATE, DEN_TASK_UPDATE_CURRENT_STATUS, DEN_TASK_WRITE_INTENT, DEN_TOOL_OUTPUT_READ,
    DEN_USER_GET_CURRENT, DEN_WEB_FETCH, DEN_WEB_FETCH_LEGACY_PROVIDER, DEN_WEB_SEARCH,
    DEN_WORK_CATALOG, DEN_WORK_DISPATCH, DEN_WORK_RUN_CANCEL, DEN_WORK_RUN_GET, DEN_WORK_RUN_LIST,
};

pub fn provider_aliases_for_tool(name: &str) -> &'static [&'static str] {
    match name {
        DEN_WEB_FETCH => &[DEN_WEB_FETCH_LEGACY_PROVIDER],
        DEN_WEB_SEARCH => &["den_web_search"],
        DEN_CONVERSATION_SET_TITLE => &[
            "set_thread_title",
            "rename_conversation",
            "rename_thread",
            "conversation_rename",
        ],
        DEN_PLAN_MODE_RECORD_APPROVAL => &["approve_plan", "approve_current_plan"],
        DEN_BEAR_ENVIRONMENT => &["den_bear_environment"],
        DEN_SITUATION_GET => &[DEN_SITUATION_GET_LEGACY_PROVIDER, "den_situation_get"],
        DEN_MEMORY_WRITE_ENTRY => &["den_memory_write_entry"],
        DEN_MEMORY_STATUS => &["den_memory_status"],
        DEN_MEMORY_TREE => &[DEN_MEMORY_TREE_LEGACY_PROVIDER, "den_memory_tree"],
        DEN_MEMORY_READ => &["den_memory_read"],
        DEN_MEMORY_SEARCH => &["den_memory_search"],
        DEN_MEMORY_ORIENT_WORK_SURFACE => &["den_memory_orient_work_surface"],
        DEN_MEMORY_REQUEST_REVIEW => &["den_memory_request_review"],
        DEN_PROMPT_MEMORY_UPSERT => &["den_prompt_memory_upsert"],
        DEN_PROMPT_MEMORY_LIST => &["den_prompt_memory_list"],
        DEN_PROMPT_MEMORY_PATCH => &["den_prompt_memory_patch"],
        DEN_MEMORY_LIST_PROPOSALS => &["den_memory_list_proposals"],
        DEN_MEMORY_READ_PROPOSAL => &["den_memory_read_proposal"],
        DEN_MEMORY_RESOLVE_PROPOSAL => &["den_memory_resolve_proposal"],
        DEN_MEMORY_APPLY_CORE_UPDATE => &["den_memory_apply_core_update"],
        DEN_MEMORY_MARK_LIFECYCLE => &["den_memory_mark_lifecycle"],

        _ => &[],
    }
}

pub fn is_builtin_den_tool(name: &str) -> bool {
    matches!(
        name,
        DEN_BEAR_GET_SELF
            | DEN_USER_GET_CURRENT
            | DEN_BEAR_LIST_MEMBERS
            | DEN_CAPABILITIES_LIST_SELF
            | DEN_CAPABILITY_SEARCH
            | DEN_CAPABILITY_DESCRIBE
            | DEN_CHANNEL_GET_CONTEXT
            | DEN_POLICY_GET_SELF
            | DEN_BEAR_ENVIRONMENT
            | DEN_CONVERSATION_SET_TITLE
            | DEN_WEB_FETCH
            | DEN_WEB_SEARCH
            | DEN_TOOL_OUTPUT_READ
            | DEN_SITUATION_GET
            | DEN_MEMORY_WRITE_ENTRY
            | DEN_MEMORY_STATUS
            | DEN_MEMORY_TREE
            | DEN_MEMORY_READ
            | DEN_MEMORY_SEARCH
            | DEN_ENTITY_BROWSE
            | DEN_ENTITY_RESOLVE
            | DEN_ENTITY_LINK_MEMORY
            | DEN_ENTITY_MERGE
            | DEN_ENTITY_SPLIT
            | DEN_ENTITY_WRITE_ACCESS_RULE
            | DEN_ENTITY_WRITE_ANCHOR
            | DEN_MEMORY_ORIENT_WORK_SURFACE
            | DEN_MEMORY_CREATE_WORK_SURFACE_SCAFFOLD
            | DEN_MEMORY_REQUEST_REVIEW
            | DEN_PROMPT_MEMORY_UPSERT
            | DEN_PROMPT_MEMORY_LIST
            | DEN_PROMPT_MEMORY_PATCH
            | DEN_MEMORY_LIST_PROPOSALS
            | DEN_MEMORY_READ_PROPOSAL
            | DEN_MEMORY_RESOLVE_PROPOSAL
            | DEN_MEMORY_APPLY_CORE_UPDATE
            | DEN_MEMORY_MARK_LIFECYCLE
            | DEN_SKILL_PROPOSE
            | DEN_SKILL_APPROVE_PROPOSAL
            | DEN_SKILL_REJECT_PROPOSAL
            | DEN_TASK_LISTS_LIST
            | DEN_TASK_LISTS_GET_STATUS
            | DEN_TASK_LISTS_UPDATE
            | DEN_TASK_LISTS_REQUEST_HANDOFF
            | DEN_JOB_CREATE
            | DEN_JOB_LIST
            | DEN_JOB_GET
            | DEN_JOB_UPDATE
            | DEN_JOB_EXECUTE
            | DEN_JOB_EVALUATE_CRITERION
            | DEN_TASK_CREATE
            | DEN_TASK_LIST
            | DEN_TASK_UPDATE
            | DEN_TASK_UPDATE_CURRENT_STATUS
            | DEN_TASK_LIST_SYNC
            | DEN_TASK_LIST_CHECKOUT
            | DEN_WORK_DISPATCH
            | DEN_WORK_RUN_LIST
            | DEN_WORK_RUN_GET
            | DEN_WORK_RUN_CANCEL
            | DEN_WORK_CATALOG
            | DEN_PLAN_MODE_ENTER
            | DEN_PLAN_MODE_STATUS
            | DEN_PLAN_MODE_RECORD_APPROVAL
            | DEN_PLAN_MODE_EXIT
            | DEN_PLAN_MODE_CANCEL
            | DEN_TASK_WRITE_INTENT
            | DEN_TASK_APPROVE_INTENT
            | DEN_TASK_REJECT_INTENT
            | DEN_CORE_WRITE_RESULT_SUMMARY
            | DEN_OBSERVATION_WRITE
            | DEN_RUN_WRITE_RESULT
    )
}
